title: 
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" 
url: "" 


author: ''
# Build settings
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

paypal: 

plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate

google_analytics: 

pagination:
  enabled: true
  per_page: 15
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
