- name: Awesome T-shirt
  price: 635
  Size: Small,Medium,Large
  Color:
  OneOfAKind:
  image: http://upload.wikimedia.org/wikipedia/commons/c/c6/Grey_Tshirt.jpg
  description: This is a very awesome grey T-shirt

- name: Cool T-shirt
  price: 615
  Size: Small,Medium,Large
  Color: Blue,Red
  OneOfAKind: true
  image: http://upload.wikimedia.org/wikipedia/commons/2/24/Blue_Tshirt.jpg
  description: This is a really cool blue T-shirt